meta_product_name: "Be Romanntic"
meta_title: "Be Romantic - Be Romanntic"
meta_description: "Relevant description"
meta_image: "logo.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
