meta_product_name: "Be Romanntic"

meta_title: "Be Romantic - Le premier site qui vous aide à garder votre conjoint"
meta_description: "Vous voulez raviver la flamme ? Faire des petites intentions avec votre conjointe? suivez le guide, beromantic vous aide à avoir une vie de couple heureuse et remplie"
meta_image: "BeRomantic_logo_1" # should exist in `app/assets/images/`

twitter_account: "@product_twitter_account"   # required for Twitter Cards
